<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <title>Design</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="frontend/css/normalize.css" />
    <link rel="stylesheet" type="text/css" href="frontend/css/style.css" />
  

    <!--<script src="js/jquery.js"></script>-->
   
</head>
    <body>
    <!-- NAVIGACE -->	
	<nav id="navigace">
		<a href="/" class="logo">HOME</a>
		<ul>
			<li><a href="#">lorem</a></li>
			<li><a href="#">ipsum</a></li>
			<li><a href="#">lorem</a></li>
		</ul>
	</nav>

	<!-- HEADER -->
	<header id="hlavicka">
		<h1>Administrace</h1>
		<a href="#" class="btn">Vstup</a>
	</header>

	<main>
		<div class="kalendar">
			<?php $this->controller->renderTemplate(); ?>
		</div>
	</main>

    </body>
</html>